openapi: 3.0.1
info:
  title: Challenge API
  version: 1.0.0
tags:
  - name: Category
  - name: Product

paths:
  /category/:
    post:
      tags:
        - Category
      description: Category route
      parameters:
        - in: header
          name: x-api-token
          description: Token
          required: true
          schema:
            type: string
      requestBody:
        description: the body
        content:
          application/json:
            schema:
              type: object
              readOnly: true
              description: object category
              properties:
                data:
                    type: array
                    properties:
                        name:
                            type: string
                        description:
                            type: string
      responses:
        "200":
          description: The response ok
        "400":
          description: The response error
        "500":
          description: Internal server error
  /category /:
    get:
      tags:
        - Category
      description: Category route
      parameters:
        - in: header
          name: x-api-token
          description: Token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The response ok
        "400":
          description: The response error
        "500":
          description: Internal server error
  /category/{id}:
    get:
      tags:
        - Category
      description: Category route
      parameters:
        - in: header
          name: x-api-token
          description: Token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The response ok
        "400":
          description: The response error
        "500":
          description: Internal server error
  /category / {id}:
    put:
      tags:
        - Category
      description: Category route
      parameters:
        - in: header
          name: x-api-token
          description: Token
          required: true
          schema:
            type: string
      requestBody:
        description: the body
        content:
          application/json:
            schema:
              type: object
              readOnly: true
              description: object category
              properties:
                data:
                    type: array
                    properties:
                        name:
                            type: string
                        description:
                            type: string
      responses:
        "200":
          description: The response ok
        "400":
          description: The response error
        "500":
          description: Internal server error
  /category/ {id}:
    delete:
      tags:
        - Category
      description: Category route
      parameters:
        - in: header
          name: x-api-token
          description: Token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The response ok
        "400":
          description: The response error
        "500":
          description: Internal server error
  /product/:
    post:
      tags:
        - Product
      description: Product route
      parameters:
        - in: header
          name: x-api-token
          description: Token
          required: true
          schema:
            type: string
      requestBody:
        description: the body
        content:
          application/json:
            schema:
              type: object
              readOnly: true
              description: object product
              properties:
                data:
                    type: array
                    properties:
                        name:
                            type: string
                        description:
                            type: string
                        value:
                            type: integer
                        category_id:
                            type: integer
      responses:
        "200":
          description: The response ok
        "400":
          description: The response error
        "500":
          description: Internal server error
  /product/{category_name}/import:
    post:
      tags:
        - Product
      description: Product route
      parameters:
        - in: header
          name: x-api-token
          description: Token
          required: true
          schema:
            type: string
        - in: path
          name: category_name
          description: Name of category
          required: true
          schema:
            type: string
      requestBody:
        description: the body
        content:
          application/json:
            schema:
              type: object
              readOnly: true
              description: object product
              properties:
                data:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                            type: string
                        description:
                            type: string
                        value:
                            type: integer
      responses:
        "200":
          description: The response ok
        "400":
          description: The response error
        "500":
          description: Internal server error
  /product/{category_name}/export:
    get:
      tags:
        - Product
      description: Product route
      parameters:
        - in: header
          name: x-api-token
          description: Token
          required: true
          schema:
            type: string
        - in: path
          name: category_name
          description: Param
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The response ok
        "400":
          description: The response error
        "500":
          description: Internal server error
  /product /:
    get:
      tags:
        - Product
      description: Product route
      parameters:
        - in: header
          name: x-api-token
          description: Token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The response ok
        "400":
          description: The response error
        "500":
          description: Internal server error
  /product/{id}:
    get:
      tags:
        - Product
      description: Product route
      parameters:
        - in: header
          name: x-api-token
          description: Token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The response ok
        "400":
          description: The response error
        "500":
          description: Internal server error
  /product / {id}:
    put:
      tags:
        - Product
      description: Product route
      parameters:
        - in: header
          name: x-api-token
          description: Token
          required: true
          schema:
            type: string
      requestBody:
        description: the body
        content:
          application/json:
            schema:
              type: object
              readOnly: true
              description: object product
              properties:
                data:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                            type: string
                        description:
                            type: string
                        value:
                            type: integer
      responses:
        "200":
          description: The response ok
        "400":
          description: The response error
        "500":
          description: Internal server error
  /product/ {id}:
    delete:
      tags:
        - Product
      description: Product route
      parameters:
        - in: header
          name: x-api-token
          description: Token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The response ok
        "400":
          description: The response error
        "500":
          description: Internal server error
